services:
    app:
        build: .
        container_name: axis_pay_wallet_app
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/axis_pay_local
            - PORT=3000
            - JWT_SECRET=axis-pay-secure-jwt-secret-key
        volumes:
            # handle hot reloading
            - ./src:/app/src
            - ./package.json:/app/package.json
            - ./package-lock.json:/app/package-lock.json
            - ./tsconfig.json:/app/tsconfig.json
            - /app/node_modules
        networks:
            - axis_pay_network
        command: npm run dev
    mongodb:
        image: mongo:latest
        container_name: axis_pay_mongodb
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
        networks:
            - axis_pay_network

networks:
    axis_pay_network:
        driver: bridge

volumes:
    mongodb_data: